### ISSUE TITLE
Code is reset on screen rotate

### ISSUE THREAD

**Issue by cheese-stands-alone** [vickychijwani/kotlin-koans-android#1]
As the title says everyone the screen is rotated the code in the "task.kt" is reset and all changes are lost.

**Comment by vickychijwani** [comment]
Hey @rwhite226! 👋

I'm aware of this issue. It seems tricky to fix because the code is in a `WebView`, and there seems to be no way for me to pull out the content from it synchronously (naturally, this can't be done asynchronously because the Activity is already being destroyed -- or, wait, can it? I'll have to try it out I guess).

Any ideas/suggestions on how to do this correctly are welcome 🙂

**Comment by cheese-stands-alone** [comment]
I'm on mobile right now and and have very limited experience in Android development, so correct me if I'm wrong. It looks like you are loading and running the koans from the kotlin try website. One option it to use kotlin's jsr223 integration and compile and run the koans locally. This would probably require quite a bit of restructuring to the app, but you could just use some type of code text input instead​ of a webview. This would also allow the app to run without being connected to the internet.

**Comment by vickychijwani** [comment]
Thanks, that's useful feedback. I did have the idea to run the code locally, but I don't know how I would go about it - jsr223 in particular is new to me, but it's a great pointer! Would you have further tips on how the kotlin interpreter/compiler - which I understand is written in mixed Java+Kotlin - could be run on Android?

Regarding the code input, if I do it in a native text input then it'll be a lot more difficult to get proper syntax highlighting. In any case, the WebView here has nothing to do with being connected to the Internet, it's just a convenient way to display syntax-highlighted Kotlin code.

**Comment by vickychijwani** [comment]
@rwhite226 this is fixed in 1.1.0 (rolling out via Play Store right now). I've also switched to using a native editing widget rather than a webview for code input 🙂. However running the code still requires a connection - it's just the UI that is changed.
